### ISSUE TITLE
MediaProtect: Whitelist domains

### ISSUE THREAD

**Issue by ninjaonsafari** [JcRichards1991/Our.Shield#16]
I want to white list some domains.

- We have our umbraco on `api.domain.com`
- Our Angular website is running on `domain.com`

When i access my ng website the images getting blocked, because the hotlinking blocking the request.

**Comment by Joniff** [comment]
Sadly we have started to implement environments which allow you to set the domains relevant to your setup, BUT this code is not ready yet to be deployed. So right now, we can't do what you want, but we really want to soon, and writing towards it has already commenced.

I will updated this thread once this feature has been released. Hopefully you can bare with us, as currently this package is a Minimum Viable Product, and we have much bigger plans.

**Comment by ninjaonsafari** [comment]
The main problem is that the `umbraco application` doesn't know that i'm authorized. Because we authorize the `ng app` via `jwt`.

**How we solved it:**
In the public section we just display the image as is. And block the secured images with `our.shield`.

In the secured part, we get the image via a `ApiController` as a blob. We pass the `jwt` into the `ApiController`, so we know if the user is authorized.

Maybe it helps someone with the same issue.

**Comment by JcRichards1991** [comment]
This functionality has now been released with the ability to create environments and associate domains to an environment.

So when creating an environment, you would specify its domains as:

- api.domain.com
- domain.com

**Comment by ninjaonsafari** [comment]
After updating to 1.0.3 i get an error.
The Assembly `Our.Shield.Core.UI.AppEditorAttribute` in `Our.Shield.Core` could not be loaded.

**Comment by JcRichards1991** [comment]
That's unfortunate to hear. Is there anything being thrown within the logs or event viewer for example that may assist in resolving this issue?

**Comment by JcRichards1991** [comment]
Off the top of my head, this may be thrown due to not upgrading MediaProtection to v1.0.3 or any other shield apps you have installed.

So, can you confirm, all parts of shield have been updated to v1.0.3?

**Comment by ninjaonsafari** [comment]
@JcRichards1991 I will take a look in about an hour.

**Comment by JcRichards1991** [comment]
@ninjaonsafari - Any update on this?

**Comment by ninjaonsafari** [comment]
@JcRichards1991 yes. The update worked. But we get a js error in IE on [this line](https://github.com/JcRichards1991/Our.Shield/blob/master/src/Our.Shield.Core/App_Plugins/Shield/Backoffice/Scripts/Shield.js#L19). 

The arrow functions dont' work in IE, check [caniuse](http://caniuse.com/#feat=arrow-functions).

**Comment by JcRichards1991** [comment]
Interesting, that code shouldn't be running as it's never called: https://github.com/JcRichards1991/Our.Shield/blob/master/src/Our.Shield.Core/App_Plugins/Shield/Backoffice/Scripts/Shield.js#L69

as you can see the code is currently commented out. Feel free to remove the code from the JS file. there'll be no knock on effects from this.

**Comment by ninjaonsafari** [comment]
funny!

![](https://media.giphy.com/media/EsmlrgWNx5v0Y/giphy.gif)

I replaced the arrow function with the old `function()`.

Thanks! #h5yr

**Comment by JcRichards1991** [comment]
No worries, Glad it's working correctly!
