### ISSUE TITLE
Allow changing of back office URL without IP restricition

### ISSUE THREAD

**Issue by richarth** [JcRichards1991/Our.Shield#20]
It would be useful if you could specify an alternative URL for the back office without having to enter any IP restrictions.

**Comment by Joniff** [comment]
If everyone was sent to an alternative URL, how would anyone login to the backend ?

**Comment by richarth** [comment]
In our case the client wanted to change the back office URL from /Umbraco to something like /admin.  They are happy for anyone to be able to login from the new URL.

**Comment by akeilox** [comment]
I came across similar requests to change the /Umbraco to something not publicly known, IP restrictions werent applicable due to dynamic ip of users - but wished basic privacy of backoffice url

**Comment by JcRichards1991** [comment]
This functionality already exists. Click the remove button beside the first IP entry within the table:
![image](https://user-images.githubusercontent.com/17648147/29408106-d5b6bd6a-833e-11e7-9c89-c5a8a96da504.png)
Click Ok to the javascript confirmation popup, then save the configuration. When you next come to update the configuration, you'll need to remove the blank IP address again from the table before being able to save.

In the next release (1.0.2) this has already been updated to not add an empty IP address to the table, and therefore, less restrictive.

**Comment by akeilox** [comment]
Thats great @JcRichards1991 

Thanks for sharing it!

**Comment by JcRichards1991** [comment]
Actually, BAD ADVICE, although this allows you to save the configuration, the code behind will still check, and will still block access from all IPs. this is a minor change and I'll have a new release out later today to address this issue.

**Comment by akeilox** [comment]
Oh I see. Noted!

I would like to ask, Is there a way to manually install this on a remote server with no access to VStudio/nuget?

**Comment by JcRichards1991** [comment]
Yes, please refer to the manual: https://github.com/JcRichards1991/Our.Shield/blob/master/Docs/manual.pdf

**Comment by akeilox** [comment]
Yes, I have seen the manual, very well written.

My question was not to the point earlier, meant to ask if the upcoming update will be released as package too?

**Comment by JcRichards1991** [comment]
Sorry, yes, the new release will be as a package also

**Comment by akeilox** [comment]
Many thanks! Appreciate your work.

**Comment by JcRichards1991** [comment]
This has now been released in v1.0.2, check it out on nuget.org or on our.umbraco.org :)

**Comment by akeilox** [comment]
Thanks for the update!

I have just installed it on a test remote site, enabled Backoffice Access with custom name and remove the empty IP table and click Update. It seems however its not working when I try from a remote PC to access the new URL, it goes straight to /unauthorized url specified.
Is there a switch somewhere or am I missing something? Tried visiting the same page and deleting the empty IP address table and Update, but result is the same - remote pc goes straight to unauthorized when hitting custom backend url.

Would appreciate if you can shed some light.

**Comment by JcRichards1991** [comment]
@akeilox - That's unfortunate to hear. Can I confirm that you can see the new setting on the backoffice access app:
![image](https://user-images.githubusercontent.com/17648147/29458144-9a580242-8415-11e7-9c5c-efdaac96e0b8.png)

**Comment by akeilox** [comment]
Hi Joshua

I have installed it to a remote server which has no prior our.shield install, via package manager - saw the version number as 1.02 before installing the package.

I dont see that option in the settings, as there was no upgrade involved (no prior install) could it be the package downloaded via umbraco backend?

**Comment by akeilox** [comment]
just checked the bin folder for assembly versions;

Our.Shield.BackofficeAccess.dll version 1.0
and core dll version 1,0,1

**Comment by JcRichards1991** [comment]
Does suggest I've created the umbraco package incorrectly, all versions should be v1.0.2

I'm looking into this currently, and I'll get back to you as soon as I can regarding a way forward

**Comment by JcRichards1991** [comment]
So, When I go to install the package via umbraco backoffice package manager:

![image](https://user-images.githubusercontent.com/17648147/29458973-a264f874-8419-11e7-9923-5aa5e3219431.png)

As you can see it's referencing version 1.0.1

Where as on the our.umbraco.org website, it states the current version as 1.0.2:

![image](https://user-images.githubusercontent.com/17648147/29459025-db6d7c5e-8419-11e7-9ec3-aaaa6e4c74ab.png)

I'm not too sure why this is the case, I can only presume the package manager in the backoffice has some sort of caching to it, and therefore, hasn't been updated to reference the new version.

What you'll want to do is:

1. Download the package as a zip from here: https://our.umbraco.org/projects/backoffice-extensions/ourshield/ (either using the download button in top right hand corner, or the link within the package files bit at the bottom of the page)

2. login to the umbraco site you'd wish to install onto and navigate to the developer section >then click on the Packages node

3. Click the "install local" in the top right:
![image](https://user-images.githubusercontent.com/17648147/29459250-b6b3357e-841a-11e7-8eaa-81150d4cd505.png)

4. you should see a the above image, upload the *.zip file downloaded from step one.

5. Once uploaded the zip file you should get the following:
![image](https://user-images.githubusercontent.com/17648147/29459318-fceab300-841a-11e7-8c59-787207bf5903.png)

Where you can continue and install the correct version.

Hope it goes well and works correctly as you desire after installing the new version correctly

**Comment by akeilox** [comment]
I have installed the package on a new development system. The server is behind CloudFlare so the real IP addresses are in CF-Connecting-IP header.

My question is, how will this package handle the proxy like usage to get real IP from CF-Connecting-IP or X-Forwarded-For

**Comment by JcRichards1991** [comment]
Creating this as a new issue
