### ISSUE TITLE
Updating adds swagger, which breaks my umbraco

### ISSUE THREAD

**Issue by DontPanic345** [JcRichards1991/Our.Shield#39]
Hi there! looks like updating to version 1.1.0 has caused a problem. I was previously only using Backoffice and Frontend plugins. Now it appears swagger has broken my setup

Here is the error message I see:

`An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.`

```
[ArgumentException: A route named 'swagger_docs' is already in the route collection. Route names must be unique.
Parameter name: name]
   System.Web.Routing.RouteCollection.Add(String name, RouteBase item) +391
   System.Web.Http.HttpRouteCollectionExtensions.MapHttpRoute(HttpRouteCollection routes, String name, String routeTemplate, Object defaults, Object constraints, HttpMessageHandler handler) +160
   Swashbuckle.Application.HttpConfigurationExtensions.EnableSwagger(HttpConfiguration httpConfig, String routeTemplate, Action`1 configure) +221
   Our.Shield.Swagger.Operation.SwaggerConfig.Register() +257
```

**Comment by Joniff** [comment]
It sounds like you already have swagger (or SwashBuckle) already installed in your installation, I suggest uninstalling Our.Shield.Swagger.

If you installed Shield using Umbraco Packages as apposed to Nuget, I can suggest deleting the /bin/Our.Shield.Swagger.dll file as its the quickest way to do this.

**Comment by JcRichards1991** [comment]
Hey,

That's unfortunate to hear. As Joniff has pointed out, uninstalling the Swagger nuget package will resolve you're issue. You'll need to force uninstall this via the nuget package manager (right click on project in VS > manage nuget packages > find Our.Shield.Swagger package > expand options > tick Force uninstall > uninstall package). Swagger was added in mistake to the dependencies of Frontend Access app nuget package.

The alternative, is to remove the Swagger configuration setup in you're code base (which would look similar to https://github.com/JcRichards1991/Our.Shield/blob/c30c661c843d7b8b9d56e74148e705c18f98df04/src/Our.Shield.Swagger/Operation/Register.cs#L30) and allow the swagger app to do the configuration and gain the benefits of the security that the swagger app provides.

I can understand either option is not ideal and will have a new release soon addressing the mistake of have the dependency on Swagger App for Frontend Access

**Comment by DontPanic345** [comment]
Thanks for the help, force uninstalling the shield.swagger did fix the problem.

But I couldn't find what was causing the problem if I removed the swagger.config file in App_Start I got a different error coming from that same file referenced above. But let's leave that one for now until I want to install Swagger.
