### ISSUE TITLE
Any plans to support Cloudflare IP ?

### ISSUE THREAD

**Issue by akeilox** [JcRichards1991/Our.Shield#43]
Thank you for creating this package with great detail.

Is it possible to support CloudFlare IP ?
As you may know websites behind CloudFlare gets a proxy IP address and original IP address gets masked.

The true IP address is hidden in the header CF-Connecting-IP and/or X-Forwarded-For .
https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

My question is how can I use this package with Cloudflare header support for true IP detection?

**Comment by JcRichards1991** [comment]
Hi @akeilox 

Sorry for late reply, didn't know I had this issue raised...

This is already taken care of.

If your using shield with umbraco v7, you should have this file within your config folder of the website https://github.com/JcRichards1991/Our.Shield/blob/master-umbraco-v7/src/Our.Shield.Core/Transforms/Config/shield.config

Here you can add additional headers to check for the IP address. As you can see, OOTB, the `X-Forwarded-For` header should already be taken into consideration when checking the IP address of the user to determine whether to grant access or not.

If you don't have this file, you can copy/paste it and manually add it, then also check the following is present in your web.config - https://github.com/JcRichards1991/Our.Shield/blob/master-umbraco-v7/src/Our.Shield.Core/Transforms/Web.config.install.xdt

I hope this answers your question

Regards,
Joshua
