### ISSUE TITLE
Compatibility with Umbraco 8 or 9?

### ISSUE THREAD

**Issue by DontPanic345** [JcRichards1991/Our.Shield#54]
My question is if Shield will work with Umbraco 8 or even 9?

I'm looking at upgrading and wondering what my options are.

Thanks

**Comment by JcRichards1991** [comment]
Hi @DontPanic345 

Currently, Shield is only compatible with umbraco v7. I do have a WIP branch for a compatible version for umbraco v8, however, currently only the Core works - none of the apps (i.e. backoffice access, frontend access) do yet.

So, I do have plans to release a compatible version with umbraco v8, with a v9 down the road.

Regards,
Joshua

**Comment by DontPanic345** [comment]
great, thanks for that, looking forward to seeing that once it lands 👍
